create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  quantity integer not null default 0 check (quantity >= 0),
  quantity_in_use integer not null default 0 check (quantity_in_use >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint items_quantity_in_use_lte_quantity check (quantity_in_use <= quantity)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists items_set_updated_at on public.items;

create trigger items_set_updated_at
before update on public.items
for each row
execute function public.set_updated_at();

alter table public.items enable row level security;

-- Drop legacy anon-based policies if migrating from an earlier version
drop policy if exists "Allow public inventory reads" on public.items;
drop policy if exists "Allow public inventory inserts" on public.items;
drop policy if exists "Allow public inventory updates" on public.items;
drop policy if exists "Allow public inventory deletes" on public.items;

drop policy if exists "Allow authenticated inventory reads" on public.items;
create policy "Allow authenticated inventory reads"
on public.items
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated inventory inserts" on public.items;
create policy "Allow authenticated inventory inserts"
on public.items
for insert
to authenticated
with check (true);

drop policy if exists "Allow authenticated inventory updates" on public.items;
create policy "Allow authenticated inventory updates"
on public.items
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Allow authenticated inventory deletes" on public.items;
create policy "Allow authenticated inventory deletes"
on public.items
for delete
to authenticated
using (true);
